/**
 * Hello API Platform
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import Credentials from './model/Credentials';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse200Hydrasearch from './model/InlineResponse200Hydrasearch';
import InlineResponse200HydrasearchHydramapping from './model/InlineResponse200HydrasearchHydramapping';
import InlineResponse200Hydraview from './model/InlineResponse200Hydraview';
import OneOfUserJsonldReadContext from './model/OneOfUserJsonldReadContext';
import OneOfUserJsonldWriteContext from './model/OneOfUserJsonldWriteContext';
import Token from './model/Token';
import UserJsonldRead from './model/UserJsonldRead';
import UserJsonldWrite from './model/UserJsonldWrite';
import UserRead from './model/UserRead';
import UserWrite from './model/UserWrite';
import TokenApi from './api/TokenApi';
import UserApi from './api/UserApi';

/**
* Object.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HelloApiPlatform = require('index'); // See note below*.
* var xxxSvc = new HelloApiPlatform.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HelloApiPlatform.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HelloApiPlatform.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HelloApiPlatform.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Credentials model constructor.
     * @property {module:model/Credentials}
     */
    Credentials,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse200Hydrasearch model constructor.
     * @property {module:model/InlineResponse200Hydrasearch}
     */
    InlineResponse200Hydrasearch,

    /**
     * The InlineResponse200HydrasearchHydramapping model constructor.
     * @property {module:model/InlineResponse200HydrasearchHydramapping}
     */
    InlineResponse200HydrasearchHydramapping,

    /**
     * The InlineResponse200Hydraview model constructor.
     * @property {module:model/InlineResponse200Hydraview}
     */
    InlineResponse200Hydraview,

    /**
     * The OneOfUserJsonldReadContext model constructor.
     * @property {module:model/OneOfUserJsonldReadContext}
     */
    OneOfUserJsonldReadContext,

    /**
     * The OneOfUserJsonldWriteContext model constructor.
     * @property {module:model/OneOfUserJsonldWriteContext}
     */
    OneOfUserJsonldWriteContext,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The UserJsonldRead model constructor.
     * @property {module:model/UserJsonldRead}
     */
    UserJsonldRead,

    /**
     * The UserJsonldWrite model constructor.
     * @property {module:model/UserJsonldWrite}
     */
    UserJsonldWrite,

    /**
     * The UserRead model constructor.
     * @property {module:model/UserRead}
     */
    UserRead,

    /**
     * The UserWrite model constructor.
     * @property {module:model/UserWrite}
     */
    UserWrite,

    /**
    * The TokenApi service constructor.
    * @property {module:api/TokenApi}
    */
    TokenApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
