/**
 * Hello API Platform
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The Credentials model module.
* @module model/Credentials
* @version 1.0.0
*/
export default class Credentials {
    /**
    * Constructs a new <code>Credentials</code>.
    * @alias module:model/Credentials
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Credentials</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Credentials} obj Optional instance to populate.
    * @return {module:model/Credentials} The populated <code>Credentials</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Credentials();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {String} password
    */
    'password' = undefined;




}
