/**
 * Hello API Platform
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The InlineResponse200Hydraview model module.
* @module model/InlineResponse200Hydraview
* @version 1.0.0
*/
export default class InlineResponse200Hydraview {
    /**
    * Constructs a new <code>InlineResponse200Hydraview</code>.
    * @alias module:model/InlineResponse200Hydraview
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InlineResponse200Hydraview</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse200Hydraview} obj Optional instance to populate.
    * @return {module:model/InlineResponse200Hydraview} The populated <code>InlineResponse200Hydraview</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200Hydraview();
                        
            
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('hydra:first')) {
                obj['hydra:first'] = ApiClient.convertToType(data['hydra:first'], 'String');
            }
            if (data.hasOwnProperty('hydra:last')) {
                obj['hydra:last'] = ApiClient.convertToType(data['hydra:last'], 'String');
            }
            if (data.hasOwnProperty('hydra:previous')) {
                obj['hydra:previous'] = ApiClient.convertToType(data['hydra:previous'], 'String');
            }
            if (data.hasOwnProperty('hydra:next')) {
                obj['hydra:next'] = ApiClient.convertToType(data['hydra:next'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} @id
    */
    '@id' = undefined;
    /**
    * @member {String} @type
    */
    '@type' = undefined;
    /**
    * @member {String} hydra:first
    */
    'hydra:first' = undefined;
    /**
    * @member {String} hydra:last
    */
    'hydra:last' = undefined;
    /**
    * @member {String} hydra:previous
    */
    'hydra:previous' = undefined;
    /**
    * @member {String} hydra:next
    */
    'hydra:next' = undefined;




}
