/**
 * Hello API Platform
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The OneOfUserJsonldReadContext model module.
* @module model/OneOfUserJsonldReadContext
* @version 1.0.0
*/
export default class OneOfUserJsonldReadContext {
    /**
    * Constructs a new <code>OneOfUserJsonldReadContext</code>.
    * @alias module:model/OneOfUserJsonldReadContext
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>OneOfUserJsonldReadContext</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/OneOfUserJsonldReadContext} obj Optional instance to populate.
    * @return {module:model/OneOfUserJsonldReadContext} The populated <code>OneOfUserJsonldReadContext</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OneOfUserJsonldReadContext();
                        
            
        }
        return obj;
    }





}
