/*
 * Hello API Platform
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OneOfUserJsonldWriteContext model module.
 * @module model/OneOfUserJsonldWriteContext
 * @version 1.0.0
 */
export class OneOfUserJsonldWriteContext {
  /**
   * Constructs a new <code>OneOfUserJsonldWriteContext</code>.
   * @alias module:model/OneOfUserJsonldWriteContext
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OneOfUserJsonldWriteContext</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OneOfUserJsonldWriteContext} obj Optional instance to populate.
   * @return {module:model/OneOfUserJsonldWriteContext} The populated <code>OneOfUserJsonldWriteContext</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OneOfUserJsonldWriteContext();
    }
    return obj;
  }
}
