/*
 * Hello API Platform
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.32
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserJsonldWrite model module.
 * @module model/UserJsonldWrite
 * @version 1.0.0
 */
export class UserJsonldWrite {
  /**
   * Constructs a new <code>UserJsonldWrite</code>.
   * @alias module:model/UserJsonldWrite
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserJsonldWrite</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserJsonldWrite} obj Optional instance to populate.
   * @return {module:model/UserJsonldWrite} The populated <code>UserJsonldWrite</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserJsonldWrite();
      if (data.hasOwnProperty('@context'))
        obj.context = ApiClient.convertToType(data['@context'], Object);
      if (data.hasOwnProperty('@id'))
        obj.id = ApiClient.convertToType(data['@id'], 'String');
      if (data.hasOwnProperty('@type'))
        obj.type = ApiClient.convertToType(data['@type'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('roles'))
        obj.roles = ApiClient.convertToType(data['roles'], ['String']);
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Object} context
 */
UserJsonldWrite.prototype.context = undefined;

/**
 * @member {String} id
 */
UserJsonldWrite.prototype.id = undefined;

/**
 * @member {String} type
 */
UserJsonldWrite.prototype.type = undefined;

/**
 * @member {String} email
 */
UserJsonldWrite.prototype.email = undefined;

/**
 * @member {Array.<String>} roles
 */
UserJsonldWrite.prototype.roles = undefined;

/**
 * @member {String} password
 */
UserJsonldWrite.prototype.password = undefined;

