/**
 * Hello API Platform
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Operation from './Operation';

/**
* The UserJsonldRead model module.
* @module model/UserJsonldRead
* @version 1.0.0
*/
export default class UserJsonldRead {
    /**
    * Constructs a new <code>UserJsonldRead</code>.
    * @alias module:model/UserJsonldRead
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>UserJsonldRead</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserJsonldRead} obj Optional instance to populate.
    * @return {module:model/UserJsonldRead} The populated <code>UserJsonldRead</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserJsonldRead();
                        
            
            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], Operation);
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Operation} @context
    */
    '@context' = undefined;
    /**
    * @member {String} @id
    */
    '@id' = undefined;
    /**
    * @member {String} @type
    */
    '@type' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {Array.<String>} roles
    */
    'roles' = undefined;




}
